<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net462;netstandard2.0;net6.0</TargetFrameworks>
        <Title>NAPS2.Sane.Binaries</Title>
        <Product>NAPS2.Sane.Binaries</Product>

        <Version>1.2.2</Version>
        <PackageVersion>1.2.2</PackageVersion>
        <AssemblyVersion>1.0.0.0</AssemblyVersion>

        <Copyright>Copyright 2022-2026 Ben Olden-Cooligan (note: binaries have separate copyrights)</Copyright>
        <LangVersion>10</LangVersion>
        <Authors>Ben Olden-Cooligan</Authors>
        <Description>SANE binaries for scanning with NAPS2.Sdk</Description>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Title>NAPS2.Sane.Binaries</Title>
        <RepositoryUrl>https://github.com/cyanfish/naps2-sane</RepositoryUrl>
        <PackageProjectUrl>https://github.com/cyanfish/naps2-sane</PackageProjectUrl>
        <RepositoryType>git</RepositoryType>
        <PackageLicenseExpression>GPL-2.0-only</PackageLicenseExpression>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageTags>naps2 sane libsane scan scanning scanner</PackageTags>
        <SignAssembly>true</SignAssembly>
        <AssemblyOriginatorKeyFile>public_signing_key.snk</AssemblyOriginatorKeyFile>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="NAPS2.Sane.Binaries.targets" PackagePath="build/NAPS2.Sane.Binaries.targets" />
        <None Include="..\artifacts\mac-arm64\*.dylib">
            <Link>lib/mac-arm64/*.dylib</Link>
            <Pack>true</Pack>
            <PackageCopyToOutput>true</PackageCopyToOutput>
            <PackagePath>contentFiles/_macarm</PackagePath>
        </None>
        <None Include="..\artifacts\mac-arm64\sane\*.so">
            <Link>lib/mac-arm64/sane/*.so</Link>
            <Pack>true</Pack>
            <PackageCopyToOutput>true</PackageCopyToOutput>
            <PackagePath>contentFiles/_macarm/sane</PackagePath>
        </None>
        <None Include="..\artifacts\mac-x64\*.dylib">
            <Link>lib/mac-x64/*.dylib</Link>
            <Pack>true</Pack>
            <PackageCopyToOutput>true</PackageCopyToOutput>
            <PackagePath>contentFiles/_mac</PackagePath>
        </None>
        <None Include="..\artifacts\mac-x64\sane\*.so">
            <Link>lib/mac-x64/sane/*.so</Link>
            <Pack>true</Pack>
            <PackageCopyToOutput>true</PackageCopyToOutput>
            <PackagePath>contentFiles/_mac/sane</PackagePath>
        </None>
        <None Include="..\artifacts\config\sane\*.conf">
            <Link>lib/config/sane/*.conf</Link>
            <Pack>true</Pack>
            <PackageCopyToOutput>true</PackageCopyToOutput>
            <PackagePath>contentFiles/_config/sane</PackagePath>
        </None>
        <None Include="..\artifacts\data\hplip\*.dat">
            <Link>lib/data/hplip/*.dat</Link>
            <Pack>true</Pack>
            <PackageCopyToOutput>true</PackageCopyToOutput>
            <PackagePath>contentFiles/_data/hplip</PackagePath>
        </None>
    </ItemGroup>

    <ItemGroup>
        <None Include="..\LICENSE" Pack="true" PackagePath="\" />
        <None Include="..\README.md" Pack="true" PackagePath="\" />
        <None Include="..\artifacts\libjpeg-turbo-license.md" Pack="true" PackagePath="\" />
        <None Include="..\artifacts\libusb-authors.txt" Pack="true" PackagePath="\" />
        <None Include="..\artifacts\libusb-license.txt" Pack="true" PackagePath="\" />
        <None Include="..\artifacts\sane-backends-authors.txt" Pack="true" PackagePath="\" />
        <None Include="..\artifacts\sane-backends-license.txt" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>
